version: '3'
services:

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "password"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: username
      KAFKA_MANAGER_PASSWORD: password
      KM_ARGS: -Djava.net.preferIPv4Stack=true

  # docker run -d -p 9001:8080 -e ZK=aa.cloudm.link:2181 jpodeszwik/kafka-offset-monitor
  kafka-offset-monitor:
    image: jpodeszwik/kafka-offset-monitor
    container_name: kafka-offset-monitor
    ports:
      - 8080:8080
    environment:
      RETAIN: 2.days
      REFRESH: 10.seconds
      ZK: zookeeper:2181
