version: '2'
services:

  # https://blog.knowledgebox.online/linux/lnx-mysql-with-docker/
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/choi-ys/volumes/mysql/data:/var/lib/mysql
      - /Users/choi-ys/volumes/mysql/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mysql
      - MYSQL_USER_PASSWORD=password
    restart: always
