version: '2'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      # - {your_custom_path}:/var/lib/postgresql/data
      - /Users/choi-ys/volumes/postgresql/data:/var/lib/postgresql/data # mac
      # - /mnt/postgres/data:/var/lib/postgresql/data # windows
    restart: always
