version: '3'
services:

 # docker run -d -p 1521:1521 -p 81:81 -v {local/dir/path}}:/opt/h2-data -e H2_OPTIONS='-ifNotExists' --name=h2 oscarfonts/h2
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: oscarfonts/h2
    ports:
      - 81:81
      - 1521:1521
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - /Users/choi-ys/volumes/h2:/opt/h2-data # mac
      # - /Users/arura/h2:/opt/h2-data # windows
    restart: always
