version: '2'
services:

  zookeeper:
   container_name: zookeeper
   image: zookeeper
   ports:
     - "2181:2181"
   restart: always
 kafka:
   image: wurstmeister/kafka
   container_name: kafka
   environment:
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - "9092:9092"
   depends_on:
     - zookeeper
   restart: always
 kafka-manager:
   container_name: kafka-manager
   image: sheepkiller/kafka-manager
   ports:
     - "9000:9000"
   environment:
     ZK_HOSTS: "zookeeper:2181"
     APPLICATION_SECRET: "letmein"
   restart: always
