version: '2'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "password"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: username
      KAFKA_MANAGER_PASSWORD: password
      KM_ARGS: -Djava.net.preferIPv4Stack=true

  # docker run -it -p 9001:8080 -e ZK=<zookeeper_location> --REFRESH=10.seconds --RETAIN=2.days jpodeszwik/kafka-offset-monitor
  # docker run -d -p 9001:8080 -e ZK=aa.cloudm.link:2181 jpodeszwik/kafka-offset-monitor
  kafka-monitor:
    image: jpodeszwik/kafka-offset-monitor
    container_name: kafka-monitor
    # command: --zk zookeeper:2181 --port 8080 --refresh 10.seconds --retain 2.days
    ports:
      - 8080:8080
    environment:
      RETAIN: 2.days
      REFRESH: 10.seconds
      ZK: zookeeper:2181
