version: '3'
services:

  # https://akageun.github.io/2020/05/01/docker-compose-kafka-cluster-manager.html
  # https://www.programmersought.com/article/64294852475/
  # https://bigdatalab.tistory.com/26
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  # docker exec -it kafka bash
  # cd opt/kafka
  # ./bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic test-topic
  # ./bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
  # ./bin/kafka-topics.sh --bootstrap-server localhost:9092 test --describe | grep test
  # ./bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test-topic
  # ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test-topic --from-beginning
  # ./bin/kafka-consumer-groups.sh  --bootstrap-server localhost:9092 --list
  # ./bin/kafka-consumer-groups.sh  --bootstrap-server localhost:9092 --group dl-load-consumer --describe


  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      JMX_PORT: 9093
#      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
